"""Seed catalog for EverydayFinds (DeoDap-style everyday goods)."""

CATEGORIES = [
    {"slug": "gadgets", "label": "Gadgets"},
    {"slug": "accessories", "label": "Accessories"},
    {"slug": "home", "label": "Home & Living"},
    {"slug": "jewelry", "label": "Jewelry"},
]

PRODUCTS = [
    {
        "id": "p-storage-rack",
        "name": "Multipurpose Foldable 4-Layer Storage Rack",
        "price": 499, "mrp": 999, "category": "home",
        "image": "https://deodap.in/cdn/shop/files/4-layers-Rack-02.jpg?v=1776501400&width=1100",
        "description": "Space-saving four-layer rack for shoes, bags, accessories and everyday household storage. Foldable, sturdy and assembles in minutes.",
        "badge": "Bestseller", "rating": 4.8, "reviews": 2140,
        "features": ["4 spacious layers", "Foldable & portable", "Rust-resistant frame", "Tool-free assembly"],
    },
    {
        "id": "p-travel-tumbler",
        "name": "Premium Stainless Steel Insulated Travel Tumbler (900ML)",
        "price": 699, "mrp": 1299, "category": "home",
        "image": "https://deodap.in/cdn/shop/files/VacuumMug-02.jpg?v=1787718625&width=990",
        "description": "Durable double-wall insulated stainless steel tumbler that keeps drinks hot for 12h and cold for 24h. Leak-proof lid, perfect for travel.",
        "badge": "Trending", "rating": 4.7, "reviews": 1560,
        "features": ["900ML capacity", "12h hot / 24h cold", "Leak-proof lid", "Food-grade steel"],
    },
    {
        "id": "p-clock-birds",
        "name": "Premium Birds Designer Wooden Wall Clock",
        "price": 999, "mrp": 1999, "category": "home",
        "image": "https://deodap.in/cdn/shop/files/geebk1TYFS.png?v=1784357495&width=1100",
        "description": "Decorative multi-layer wooden wall clock with an elegant birds design. Silent sweep movement for a peaceful home.",
        "badge": "Handcrafted", "rating": 4.9, "reviews": 890,
        "features": ["Silent sweep quartz", "Layered wood art", "Easy wall mount", "Premium finish"],
    },
    {
        "id": "p-clock-7layer",
        "name": "Modern 7-Layer Wooden Wall Clock (Silent Sweep)",
        "price": 999, "mrp": 1999, "category": "home",
        "image": "https://deodap.in/cdn/shop/files/Oo1pgstBq2.png?v=1777724090&width=1100",
        "description": "Modern seven-layer wooden wall clock with a quiet silent-sweep quartz movement. A statement piece for any wall.",
        "badge": "Handcrafted", "rating": 4.8, "reviews": 760,
        "features": ["7 depth layers", "Silent sweep quartz", "Contemporary design", "Durable MDF wood"],
    },
    {
        "id": "p-clock-7layer-grey",
        "name": "Modern 7-Layer Grey Wooden Wall Clock",
        "price": 999, "mrp": 1999, "category": "home",
        "image": "https://deodap.in/cdn/shop/files/dYwfZSXzmY.png?v=1780748153&width=1100",
        "description": "Minimal grey wooden wall clock designed for living rooms, offices and bedrooms. Understated and elegant.",
        "badge": "New", "rating": 4.7, "reviews": 540,
        "features": ["Muted grey tone", "Silent movement", "Minimalist dial", "Sturdy build"],
    },
    {
        "id": "p-clock-botanical",
        "name": "Premium Grey Botanical Designer Silent Wall Clock",
        "price": 999, "mrp": 1999, "category": "home",
        "image": "https://deodap.in/cdn/shop/files/lYSt3dsKhW.png?v=1784357495&width=1100",
        "description": "Botanical-inspired grey wooden wall clock with a quiet movement and clean finish. Brings nature indoors.",
        "badge": "Handcrafted", "rating": 4.9, "reviews": 610,
        "features": ["Botanical motif", "Silent sweep quartz", "Layered craftsmanship", "Matte finish"],
    },
    {
        "id": "p-butterfly-necklace",
        "name": "Rose Gold Butterfly Pendant Necklace with Crystal Accents",
        "price": 399, "mrp": 899, "category": "jewelry",
        "image": "https://deodap.in/cdn/shop/files/KVF3z0y8b2.png?v=1787986021&width=1100",
        "description": "Rose-gold butterfly pendant necklace with sparkling crystal accents and a fine alloy chain. Everyday elegance.",
        "badge": "Bestseller", "rating": 4.8, "reviews": 1320,
        "features": ["Rose-gold plating", "Crystal accents", "Adjustable chain", "Hypoallergenic"],
    },
    {
        "id": "p-bunny-set",
        "name": "Cute White Enamel Bunny Pendant & Earrings Set",
        "price": 449, "mrp": 999, "category": "jewelry",
        "image": "https://deodap.in/cdn/shop/files/DkUOUDKLQH.jpg?v=1784523706&width=1100",
        "description": "Adorable white enamel bunny pendant necklace with matching crystal drop earrings. A charming gift set.",
        "badge": "Gift Set", "rating": 4.7, "reviews": 880,
        "features": ["Necklace + earrings", "Enamel finish", "Crystal drops", "Gift-ready"],
    },
    {
        "id": "p-blue-earrings",
        "name": "Blue Stone Crystal Long Dangle Party Earrings",
        "price": 349, "mrp": 799, "category": "jewelry",
        "image": "https://deodap.in/cdn/shop/files/sZyjuvXLNR.jpg?v=1786164070&width=1100",
        "description": "Blue stone crystal long dangle earrings for women. Party-ready sparkle with a lightweight feel.",
        "badge": "Trending", "rating": 4.6, "reviews": 720,
        "features": ["Long dangle design", "Blue crystal stones", "Lightweight", "Secure hooks"],
    },
    {
        "id": "p-black-earrings",
        "name": "Black Stone Crystal Drop Earrings",
        "price": 349, "mrp": 799, "category": "jewelry",
        "image": "https://deodap.in/cdn/shop/files/SQhKv4896B.jpg?v=1786164071&width=990",
        "description": "Stylish black stone crystal drop earrings for women. Elegant party wear that pairs with any outfit.",
        "badge": "New", "rating": 4.6, "reviews": 530,
        "features": ["Black crystal drops", "Party wear", "Anti-tarnish", "Comfortable fit"],
    },
    {
        "id": "p-panjo-set",
        "name": "AD Stone Micro Gold Panjo Bracelet & Ring Set",
        "price": 599, "mrp": 1299, "category": "jewelry",
        "image": "https://deodap.in/cdn/shop/files/jantgb3Sar.jpg?v=1787723852&width=1100",
        "description": "AD stone micro-gold panjo with attached ring and bracelet in white and red stones. Traditional statement jewellery.",
        "badge": "Premium", "rating": 4.8, "reviews": 410,
        "features": ["Panjo + ring + bracelet", "AD stones", "Micro-gold plating", "Adjustable"],
    },
    {
        "id": "p-red-clover-bracelet",
        "name": "Red Clover Design Gold-Tone Bracelet",
        "price": 399, "mrp": 899, "category": "jewelry",
        "image": "https://deodap.in/cdn/shop/files/lHXvV7UgeZ.jpg?v=1786164071&width=1100",
        "description": "Red clover design gold-tone bracelet for women. A stylish fashion accessory for daily and party wear.",
        "badge": "Trending", "rating": 4.7, "reviews": 690,
        "features": ["Clover motif", "Gold-tone finish", "Adjustable clasp", "Skin-friendly"],
    },
    {
        "id": "p-keyboard-keychain",
        "name": "Mini Mechanical Keyboard Keychain (RGB LED, 4-Key)",
        "price": 399, "mrp": 599, "category": "gadgets",
        "image": "https://images.meesho.com/images/products/941222900/uakam_512.webp?width=512",
        "description": "Four clicky mechanical keys with RGB LED lighting. A fidget-friendly desk gadget for gamers and keyboard lovers.",
        "badge": "Fun", "rating": 4.6, "reviews": 980,
        "features": ["4 clicky keys", "RGB LED", "Fidget toy", "Keychain clip"],
    },
    {
        "id": "p-star-projector",
        "name": "USB Star Projector & Disco Light",
        "price": 299, "mrp": 549, "category": "gadgets",
        "image": "https://deodap.in/cdn/shop/files/7397_1500x1500_c9375e48-b802-473c-91fa-74f7d8e5dbdb.jpg?v=1786165361&width=990",
        "description": "USB-powered dual-mode star projector and mini disco light with an adjustable flexible neck. Instant party mood.",
        "badge": "Trending", "rating": 4.5, "reviews": 1240,
        "features": ["Star + disco modes", "USB powered", "Flexible neck", "Ambient lighting"],
    },
    {
        "id": "p-ring-light",
        "name": "Selfie Flash Ring Light",
        "price": 299, "mrp": 499, "category": "gadgets",
        "image": "https://cdn.shopify.com/s/files/1/0782/3284/6646/products/01_9517595e-8d48-451f-91b7-e252bf2d5beb.jpg?v=1768886580",
        "description": "Portable clip-on selfie ring light with bright, even illumination for photos, videos and video calls.",
        "badge": "Bestseller", "rating": 4.6, "reviews": 1710,
        "features": ["3 light modes", "Clip-on design", "Rechargeable", "Universal fit"],
    },
    {
        "id": "p-led-keychain",
        "name": "LED Keychain Flashlight (Bottle Opener)",
        "price": 249, "mrp": 399, "category": "gadgets",
        "image": "https://deodap.in/cdn/shop/files/17784.png?v=1786443012&width=990",
        "description": "Compact LED keychain flashlight with multiple light modes, a built-in bottle opener and a portable clip.",
        "badge": "Handy", "rating": 4.5, "reviews": 640,
        "features": ["Multiple modes", "Bottle opener", "Keychain clip", "Pocket-size"],
    },
    {
        "id": "p-usb-lamp",
        "name": "Flexible USB LED Light Lamp",
        "price": 99, "mrp": 199, "category": "gadgets",
        "image": "https://deodap.in/cdn/shop/files/0315.png?v=1786443590",
        "description": "Flexible gooseneck USB light with an eye-safe diffuser. Plugs into any laptop, power bank or charger for instant desk lighting.",
        "badge": "Value", "rating": 4.4, "reviews": 2200,
        "features": ["Flexible gooseneck", "Eye-safe glow", "Plug & play", "Ultra portable"],
    },
    {
        "id": "p-tally-counter",
        "name": "Digital Finger Tally Counter",
        "price": 99, "mrp": 149, "category": "gadgets",
        "image": "https://deodap.in/cdn/shop/files/02_tally-counter.jpg?v=1778907683&width=990",
        "description": "Compact digital finger counter with a clear LCD display and a comfortable adjustable strap. Great for counting anything.",
        "badge": "Value", "rating": 4.5, "reviews": 430,
        "features": ["Clear LCD", "Adjustable strap", "One-touch reset", "Long battery life"],
    },
    {
        "id": "p-3in1-cable",
        "name": "3-in-1 Multi Charging Cable",
        "price": 199, "mrp": 349, "category": "accessories",
        "image": "https://deodap.in/cdn/shop/files/3-in-1-Charger-Cable-01.jpg?v=1764304493&width=990",
        "description": "Durable braided universal charging cable with Type-C, Micro USB and Lightning connectors in one.",
        "badge": "Bestseller", "rating": 4.6, "reviews": 1890,
        "features": ["Type-C + Micro + Lightning", "Braided & durable", "Fast charge", "Tangle-free"],
    },
    {
        "id": "p-screen-magnifier",
        "name": "Mobile Video Screen Magnifier",
        "price": 249, "mrp": 449, "category": "accessories",
        "image": "https://cdn.shopify.com/s/files/1/0782/3284/6646/files/1333.png?v=1786096531",
        "description": "Foldable mobile screen amplifier that enlarges phone videos for a more comfortable, cinema-like viewing experience.",
        "badge": "Trending", "rating": 4.3, "reviews": 560,
        "features": ["3D magnification", "Foldable stand", "Fits most phones", "Eye comfort"],
    },
    {
        "id": "p-5in1-kit",
        "name": "5-in-1 Charging Kit",
        "price": 349, "mrp": 599, "category": "accessories",
        "image": "https://cdn.shopify.com/s/files/1/0782/3284/6646/files/07_18032b79-a0f6-4d9a-9694-1a92aea595b0.jpg?v=1737616420",
        "description": "Universal 5-in-1 charging cable kit with adapters, SIM tools, storage case and phone stand. Travel essential.",
        "badge": "Combo", "rating": 4.5, "reviews": 720,
        "features": ["All-in-one kit", "Storage case", "Phone stand", "SIM tools"],
    },
    {
        "id": "p-mini-fan",
        "name": "USB Rechargeable Mini Cartoon Fan",
        "price": 249, "mrp": 399, "category": "gadgets",
        "image": "https://cdn.shopify.com/s/files/1/0782/3284/6646/files/01_efa03536-bd85-46ef-b68d-d8574e4e4526.jpg?v=1767873922",
        "description": "Cute compact rechargeable mini fan for handheld or desk use, with simple one-button operation.",
        "badge": "Cute", "rating": 4.4, "reviews": 980,
        "features": ["Rechargeable", "Handheld or desk", "Quiet motor", "One-button"],
    },
    {
        "id": "p-hologram-lamp",
        "name": "3D Hologram LED Night Lamp",
        "price": 349, "mrp": 599, "category": "home",
        "image": "https://cdn.shopify.com/s/files/1/0782/3284/6646/files/8a75d758-ad92-41ac-9447-09af0a1ad4d3.jpg?v=1788335809",
        "description": "Energy-saving 3D illusion LED night lamp with a soft glow for bedrooms, living rooms and gifting.",
        "badge": "Gift Idea", "rating": 4.7, "reviews": 1120,
        "features": ["3D illusion", "Soft night glow", "Energy saving", "Perfect gift"],
    },
    {
        "id": "p-wireless-mouse",
        "name": "Wireless Mouse (Bluetooth / USB)",
        "price": 349, "mrp": 599, "category": "accessories",
        "image": "https://cdn.shopify.com/s/files/1/0782/3284/6646/files/Wireless-Mouse-01.jpg?v=1761820397",
        "description": "Slim portable wireless mouse with Bluetooth and 2.4GHz USB connectivity for laptops and desktops.",
        "badge": "New", "rating": 4.5, "reviews": 470,
        "features": ["Bluetooth + 2.4GHz", "Silent clicks", "Slim & portable", "Long battery"],
    },
]
